version: '3.8'

services:
  surf-novel:
    container_name: surf-novel
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_AUTH_SECRET: ${NEXT_AUTH_SECRET}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
    restart: always
    ports:
      - 3000:3000
    environment:
      POSTGRES_PRISMA_URL: postgresql://postgres:postgres@postgres:5432/surf_novel_db
    networks:
      - surf_novel_network

volumes:
  postgres_data:

networks:
  surf_novel_network:
    external: true