version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surf_novel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - surf_novel_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d surf_novel_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  surf_novel_network:
    external: true  # 使用外部网络