version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surf_novel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - surf_novel_network
  surf-novel:
    container_name: surf-novel
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_AUTH_SECRET: ${NEXT_AUTH_SECRET}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
    restart: always
    ports:
      - 3000:3000
    environment:
      POSTGRES_PRISMA_URL: postgresql://postgres:postgres@postgres:5432/surf_novel_db
    depends_on:
      - postgres
    networks:
      - surf_novel_network

volumes:
  postgres_data:

networks:
  surf_novel_network:
    external: true