import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '@/lib/ThemeContext';
import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import { getLocale, getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Surf Novel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { lang: string }; 
}) {
  // Get the current locale from the params
  const locale = await getLocale();
  // Load messages for the current locale
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <ThemeProvider>
        <html lang={locale}>
          <body
            className={`antialiased`}
          >
            {children}
          </body>
        </html>
      </ThemeProvider>
    </NextIntlClientProvider>
  );
}
